<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Svchost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="pictures\*.jpeg" />
    <EmbeddedResource Include="pictures\*.jpg" />
    <EmbeddedResource Include="pictures\*.png" />
    <EmbeddedResource Include="pictures\*.bmp" />
    <EmbeddedResource Include="pictures\*.gif" />
  </ItemGroup>

  <ItemGroup>
    <None Update="images\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
